[build]
target = "riscv32imc-esp-espidf"

[target.riscv32imc-esp-espidf]
linker = "ldproxy"
runner = "espflash flash -T partations.csv --bootloader bootloader.bin --monitor"
rustflags = ["--cfg", "espidf_time64"]

[unstable]
build-std = ["std", "panic_abort"]

[env]
MCU = "esp32c3"
ESP_IDF_VERSION = "v5.2.1"
IDF_PATH = "/data/esp-idf/"
ESP_IDF_TOOLS_INSTALL_DIR = "global"
#ESP_IDF_COMPONENT_MANAGER = "true"
ESP_IDF_SDKCONFIG = "sdkconfig"
ESP_IDF_SDKCONFIG_DEFAULTS = "sdkconfig.defaults"
